#!/bin/bash
echo "Checking JAMEY 3.0 Cursor setup..."
echo "✅ .cursorignore exists" && test -f .cursorignore && echo "FOUND" || echo "MISSING"
echo "✅ .cursorrules exists" && test -f .cursorrules && echo "FOUND" || echo "MISSING"
echo "✅ .cursor directory exists" && test -d .cursor && echo "FOUND" || echo "MISSING"
echo "✅ docs directory exists" && test -d docs && echo "FOUND" || echo "MISSING"
echo ""
echo "Files in .cursor/rules:"
ls -la .cursor/rules/ 2>/dev/null || echo "No rules directory"
echo ""
echo "Files in .cursor/prompts:"
ls -la .cursor/prompts/ 2>/dev/null || echo "No prompts directory"
echo ""
echo "JAMEY 3.0 Cursor setup complete!"
echo "Enable codebase indexing in Cursor settings for optimal AI assistance."
